Updates for mac

diff --git a/install.conf.yaml b/install.conf.yaml
--- a/install.conf.yaml
+++ b/install.conf.yaml
@@ -33,56 +33,70 @@
       path: bash/bash_logout
 
 - shell:
+  - description: Installing submodules
+    command: git submodule update --init --recursive
+
+- shell:
   - description: Build vimproc
     command: |
-      if [ ! -d ~/.vim/bundle/vimproc.vim ]; then
-        exit 0
+      if [ -d ~/.vim/bundle/vimproc.vim ]; then
+          cd ~/.vim/bundle/vimproc.vim
+          eval "make"
+      else
+          echo "VIMPROC INSTALLATION FAILED"
       fi
-      cd ~/.vim/bundle/vimproc.vim
-      eval "make"
 
 - shell:
   - description: Build YouCompleteMe
     command: |
-      if [ ! -d ~/.vim/bundle/YouCompleteMe ] || \
-          [ -f ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so ]; then
-          exit 0
+      cmakeinstalled=$(type cmake 2>&1 | grep "cmake is" | wc -l)
+      if [ $cmakeinstalled = 0 ]; then
+          if [[ "$OSTYPE" == "darwin"* ]]; then
+              echo "Installing cmake with brew..." > /dev/tty
+              brew install cmake > /dev/tty 2>&1 || true
+              cd ~/.vim/bundle/YouCompleteMe
+              eval "./install.py --clang-completer > /dev/tty 2>&1"
+          elif [[ "$OSTYPE" == "linux"* ]]; then
+              echo "Installing required packages: build-essential cmake python-dev..." > /dev/tty
+                  sudo apt-get install build-essential cmake python-dev < /dev/tty > /dev/tty 2>&1
+                  cd ~/.vim/bundle/YouCompleteMe
+                  eval "./install.py --clang-completer > /dev/tty 2>&1"
+          else
+              echo "UNKNOWN OS FOR CMAKE"
+          fi
       fi
-      echo -n "Build YouCompleteMe? (May require additional packages) [y|N] " > /dev/tty
-      read choice < /dev/tty
-      case "$choice" in
-          y|Y )
-              break;;
-          * )
-              exit 0;;
-      esac
-      os=$(uname)
-      if echo "${os}" | grep -iq "darwin"; then
-          echo "Installing cmake with brew." > /dev/tty
-          brew install cmake > /dev/tty 2>&1
-      elif echo "${os}" | grep -iq "linux"; then
-          echo "Installing required packages: build-essential cmake python-dev" > /dev/tty
-              sudo apt-get install build-essential cmake python-dev < /dev/tty > /dev/tty 2>&1
-      else
-          echo "Unknown OS: ${os}. Attempting to build anyway." > /dev/tty
+      if [ $? -ne 0  ]; then
+          echo "CMAKE INSTALLATION ERROR"
       fi
-      if [ $? -ne 0 ]; then
-          exit 1
-      fi
-      echo -n "Enter build options (default: --clang-completer --gocode-completer). Give a space for no args.\n> " > /dev/tty
-      read options < /dev/tty
-      if [ -n "${options}" ]; then
-          options="--clang-completer --gocode-completer"
-      fi
-      cd ~/.vim/bundle/YouCompleteMe
-      eval "./install.py ${options} > /dev/tty 2>&1"
+
+- shell:
   - description: Create VIM backup, swap, and undo directories
     command: |
       mkdir -p ~/.vim/backup_files/
       mkdir -p ~/.vim/swap_files/
       mkdir -p ~/.vim/undo_files/
-  - description: Create development directory
-    command: mkdir -p ~/dev
-  - description: Installing submodules
-    command: git submodule update --init --recursive
 
+- shell:
+  - description: Create development directory
+    command: |
+      if [ ! -d ~/dev ]; then
+          mkdir -p ~/dev
+      fi
+
+- shell:
+  - description: Install nvm
+    command: |
+      if hash nvm 2>/dev/null; then
+        echo "NVM ALREADY INSTALLED"
+      else
+        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
+      fi
+
+- shell:
+  - description: Create .nvmrc file
+    command: |
+      if [ -f ~/.nvmrc ]; then
+          echo "NVMRC FILE ALREADY EXISTS"
+      else
+          echo "lts/boron" > ~/.nvmrc
+      fi
